### ISSUE TITLE
Still maintained? (Update Dependencies?)

### ISSUE THREAD

**Issue by nelsonic** [indexzero/ps-tree#10]
Hi @indexzero 
is this module still maintained?
Do you have plans to update it?
e.g. dependencies: 
[![Dependency Status](https://david-dm.org/indexzero/ps-tree.svg)](https://david-dm.org/indexzero/ps-tree)

Would you accept a PR with tests?

**Comment by indexzero** [comment]
@nelsonic a PR would be welcome, but I'm not actively maintaining it. Would you like to be the new head maintainer? :smile:

**Comment by nelsonic** [comment]
@indexzero I've added some basic tests on a branch: https://github.com/nelsonic/ps-tree/issues/1
But unable to get past 92% coverage because of the `if(!module.parent)` which allows the script to be called directly:
```js
if(!module.parent) {
  childrenOfPid(process.argv[2] || 1, function (err, data) {
  console.log(data)
  })
```
I tried to execute the file from inside my test:
```js
  var child = cp.exec("node ./index.js", function(error, data) {
    console.log('data: ' + data.length);
    if (error !== null) {
        console.log(red('exec error: ' + error));
    }
  })
```
But that still does not improve coverage...

If you can live without 100% test coverage I can submit the PR.

**Comment by indexzero** [comment]
I would be happy to remove the `!module.parent` part all together and make that a separate `bin/ps-tree` script.

**Comment by nelsonic** [comment]
Ok. I can do that.
But... when I try to update the depdency to: `"event-stream": "3.3.0"` the tests fail because **event-stream** made a breaking change to their API.
Next steps:
1. I will add a bin/ps-tree script to invoke the module from command line
2. Remove the test I had written to invoke the script (without require-ing it - trying to exercise the `!module.parent` lines.
3. Update the dependency on **event-stream**
4. Update **index.js** to conform to the latest event-stream api.
5. Re-run tests
Will keep you posted. :+1:

**Comment by nelsonic** [comment]
@indexzero I have substituted:
```js
if(!module.parent) {
  childrenOfPid(process.argv[2] || 1, function (err, data) {
  console.log(data)
  })
}
```
for **./bin/ps-tree.js** containing:
```js
#!/usr/bin/env node
'use strict';
require('../')(process.argv[2] || 1, function (err, data) {
  console.log(data)
});
```
As a result we get 100% test coverage. :+1:

**Comment by nelsonic** [comment]
Build passes: https://travis-ci.org/nelsonic/ps-tree/builds/56141651
Submitting PR.

**Comment by nelsonic** [comment]
@indexzero should I do a *major* ***version bump*** in package.json or leave that to you?
