### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by fritx** [indexzero/ps-tree#13]
How do you guys think about getting this work in Windows?
There is no `ps` command in my Windows. 
I'm currently trying this one: https://github.com/1j01/process-tree

**Comment by indexzero** [comment]
A pull-request would be welcome for this. The module you linked to has the command to run for Windows: https://github.com/1j01/process-tree/blob/master/index.coffee#L8. I'd like to setup Appveyor as well to ensure we don't break Windows in the future. 

... @nelsonic what do you think?

**Comment by nelsonic** [comment]
@indexzero yes to Appveyor as a Windows CI tool. 
@fritx if you have time to prepare a PR that would be sweet. :+1:

**Comment by zixia** [comment]
would love to use this module if support windows... because my code need to run both linux & windows.

**Comment by zixia** [comment]
@indexzero I had just finished a runable win32 version of ps-tree, include the following changes:

# Code:
1. use `wmic.exe` to simulate `ps` under win32 platform.
1. map output header of wmic to ps
1. strip the linux ` <defunct> ` from the output

# Test
1. modify `istanbul` command line to support win32
1. use npm module `tree-kill` to replace the `kill` to support win32
1. use npm module `cross-env` to enable set environment variable in package.json

Hope this helps. :)
