### ISSUE TITLE
Darwin(mac/OSX) has different head name of COMMAND -> COMM

### ISSUE THREAD

**Issue by zixia** [indexzero/ps-tree#18]
in darwin, the ps output header is COMM, instead of COMMAND

to keep the consistency, should rename COMM to COMMAND in darwin platform.

``` shell
$ ps -A -o comm,ppid,pid,stat
COMM              PPID   PID STAT
/sbin/launchd        0     1 Ss  
/usr/libexec/Use     1    43 Ss  
```

**Comment by zixia** [comment]
this bug broken my code under darwin. hope this fix will publish to npm soon.

**Comment by zixia** [comment]
could we fix this issue?

**Comment by whitecolor** [comment]
@zixia you could make a PR

**Comment by zixia** [comment]
@whitecolor thanks.

It's already in my pull request #17 

please have a look over there. :)

**Comment by whitecolor** [comment]
I myself waiting for @indexzero

**Comment by zixia** [comment]
ping @indexzero

**Comment by soyuka** [comment]
https://github.com/zixia/ps-tree/pull/1 couldn't one allow more maintainers on this repository?

**Comment by simonepri** [comment]
Lets close also this @zixia 
We have https://github.com/indexzero/ps-tree/pull/17
