### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by atrauzzi** [indexzero/ps-tree#22]
Would love to see official TS definitions included!

**Comment by nelsonic** [comment]
@atrauzzi will TypeScript definitions improve _performance_ or _reliability_ of the _existing_ code? 🤔 
If you are proposing the addition of a _feature_ and want to make the code clearer that's different.
But adopting a Type System just for the sake of it seems like adding _complexity_ to this rather _simple_ module.

**Comment by atrauzzi** [comment]
@nelsonic - I'm not sure I understand why you'd focus on the performance or reliability of the code in relation to this request.  Typing information improves the reach of the code by allowing people who are using TypeScript to gain insights into the API.

Moreover, without typing information, people using strict checks in TypeScript will be given a compilation error upon use of this library because it is implicitly typed as `any`.

So -- I mean, if performance and reliability are the only two criteria by which you gauge the merit of anything, reliability would be it as typings improve static analysis of usages of this library.

Plenty of other libraries out there adding typing information and TS has some pretty decent reach these days.  Would be super cool if this one did as well!

**Comment by atrauzzi** [comment]
Also note: You don't have to adopt a type system within your code.  You simply need to provide a header file that annotates the public surface area (small) of this library.

**Comment by nelsonic** [comment]
@atrauzzi what I don't _understand_ is why you would want to add a layer of _complexity_ on top of such a simple module without a _clear_ benefit to the _millions_ of _existing_ users.

If there was something _specific_ about the _existing_ JS code that was _incomprehensible_ in it's _current_ state I would _support_ the idea of adding TS annotations. 
But you are proposing sprinkling glitter on something that is _already_ working as expected.
_How_ are you _using_ `ps-tree` in your code?
Did you find the _interface_/API "too complex" to understand in it's current form?

**Comment by nelsonic** [comment]
I _worry_ when people want to add layers of _needless_ complexity to _existing_ code just for the sake of following a trend.

**Comment by atrauzzi** [comment]
Wow.
