### ISSUE TITLE
Dependency attack specifically targeting ps-tree

### ISSUE THREAD

**Issue by FallingSnow** [indexzero/ps-tree#33]
One of your dependencies (event-stream) has an injection that specifically targets this package. Update to `event-stream` to 4.x to remove it. More info: https://github.com/dominictarr/event-stream/issues/116

**Comment by indexzero** [comment]
FYI `ps-tree@1.1.1` locked to `event-stream@3.3.4` (which if I read this thread correctly pre-dates the questionable changes). 

Thanks to folks for bringing it to my attention: https://github.com/indexzero/ps-tree/pull/34
